### ISSUE TITLE
how to cite database

### ISSUE THREAD

**Issue by xiangxiangtao** [suojiashun/HIT-UAV-Infrared-Thermal-Dataset#1]
Hello, how can I cite your database in my paper?

**Comment by suojiashun** [comment]
Thanks for your attention. Current you can cite this dataset by:
Jiashun Suo, Tianyi Wang, Xingzhou Zhang, Haiyang Chen, Wei Zhou, Weisong Shi. "HIT-UAV: A High-altitude Infrared Thermal Dataset for Unmanned Aerial Vehicles." arXiv preprint arXiv:2204.03245 (2022).

**Comment by xiangxiangtao** [comment]
Many thanks!
