### ISSUE TITLE
Dataset category mismatch.

### ISSUE THREAD

**Issue by feifeiwei** [suojiashun/HIT-UAV-Infrared-Thermal-Dataset#3]
你好，介绍里说有4类目标， 我使用了normal_json/annotations的标注，里面的label 有5类(0,1,2,3,4; category_id)

**Comment by suojiashun** [comment]
还有一类是 DontCare，表示分不清的物体，可以忽略。具体可以看论文https://doi.org/10.48550/arXiv.2204.03245

**Comment by feifeiwei** [comment]
好的， 谢谢， 论文里看到了。
